apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-sklearn
  namespace: seldon
spec:
  predictors:
  - name: default
    replicas: 1
    graph:
      name: regressor
      implementation: SKLEARN_SERVER
      modelUri: azureblob:newcontainer/mydata
      storageInitializerImage: seldonio/rclone-storage-initializer:1.15.0-dev  # Specify custom image here
      envSecretRefName: seldon-rclone-secret
      parameters:
        - name: method
          type: STRING
          value: predict